let data = {
  projects: [
    {
      name: "PC-98 Bot",
      img: "pc98.jpg",
      url: "https://twitter.com/PC98_bot",
      date: "7/1/2019",
      frontend: false,
      repo: "https://github.com/sbboard/pc98bot",
      tech: ["Node.js"],
      description:
        "Twitter bot that posts images from retro Japanese computer games every 4 hours. Generated a follower count of over 12,000 followers.",
    },
    {
      name: "The Invisible Sundial Website",
      url: "http://theinvisiblesundial.com/",
      img: "sun.jpg",
      date: "01/1/2021",
      frontend: true,
      repo: "https://github.com/sbboard/invisibleSundial",
      tech: ["HTML5/CSS3", "Javascript"],
      description: "Homepage for the band 'The Invisible Sundial'.",
    },
    {
      name: "1000 Tapes of Fate",
      url: "http://1000tapes.com/",
      img: "tapes.jpg",
      date: "12/31/2021",
      frontend: true,
      repo: "https://github.com/sbboard/audioAdventure",
      tech: ["HTML5/CSS3", "Javascript", "Vue.js"],
      description:
        "‘Choose Your Own Adventure’ style project where the user is led through an experience exclusively through audio. Intended to be played with eyes closed.",
    },
    {
      name: "Gang Fight",
      url: "https://gang-fight.com/",
      img: "gf.jpg",
      date: "7/24/2019",
      frontend: true,
      repo: "https://github.com/sbboard/gangfight",
      tech: ["HTML5/CSS3", "Javascript", "Vue.js"],
      description:
        "Creative brand website created with emphasis on brand styling and personality.",
    },
    {
      name: "Gang Fight API",
      img: "api.jpg",
      url: "https://gang-fight.com/api/",
      date: "4/21/2019",
      frontend: false,
      repo: "https://github.com/sbboard/gangfight_backend",
      tech: ["Node.js", "MongoDB"],
      description:
        "The backend for Gang Fight. Used to fetch various data such as latest updates as well as a database of comics.",
    },
    {
      name: "Parker Kelly Website",
      url: "http://parkerkellywebsite.com/",
      img: "parker.jpg",
      date: "2/18/18",
      frontend: true,
      tech: ["HTML5/CSS3", "Javascript", "PHP", "JQuery Mobile"],
      repo: null,
      description:
        "Portfolio website for an advertising creative. Designed with a focus on atmosphere and personality.",
    },
    {
      name: "Curosity Museum Exhibit Prototype",
      img: "nfc.jpg",
      url: "https://youtu.be/eKuc8IKYkq8",
      frontend: false,
      date: "5/10/20",
      tech: ["Python", "NFC"],
      repo: "https://github.com/echohatch1/NFC-Video-Launcher",
      description:
        "Physical interactive exhibit prototype built in collaboration with Utah's Museum of Natural Curiosity. Aimed to teach museum patrons about sorting trash using technology.",
    },
    {
      name: "Xenoblade Chronicles 2 Team Builder",
      url: "https://gang-fight.com/projects/xenoblade/tool.php",
      img: "xeno.jpg",
      frontend: true,
      date: "3/3/18",
      tech: ["HTML5/CSS3", "Javascript", "PHP"],
      repo: null,
      description:
        "Tool used to plan team layouts in the Nintendo Switch RPG Xenoblade Chronicles 2.",
    },
    {
      name: "Bonsai Bot",
      date: "1/10/20",
      tech: ["Node.js"],
      img: "bonsai.jpg",
      frontend: false,
      repo: "https://github.com/sbboard/BonsaiBot",
      url: null,
      description:
        "Discord bot created for entertainment purposes. Had the personality of a rude monkey who loved when chat participants typed the word 'bonsai'.",
    },
    {
      name: "Soviet.Futbol",
      url: "https://parkerkellywebsite.com/soviet/",
      img: "futbol.jpg",
      date: "11/15/19",
      frontend: true,
      tech: ["HTML5/CSS3", "Javascript", "WordPress", "PHP", "WooCommerce"],
      repo: null,
      description: "Online sticker shop.",
    },
    {
      name: "Gang Picross",
      url: "https://gang-fight.com/picross",
      img: "picross.jpg",
      date: "2/3/20",
      tech: ["HTML5/CSS3", "Javascript", "Vue.js"],
      frontend: true,
      repo:
        "https://github.com/sbboard/gangfight/blob/master/src/components/projects/picross.vue",
      description: "Simple nonogram game engine.",
    },
  ],
};
